### ISSUE TITLE
Keyword equals is false

### ISSUE THREAD

**Issue by ktodyruik** [kanaka/mal#177] opened 2016-02-16 23:24 UTC
Just noticed this in the CSharp version:

```
> (def! kw :abc)
:abc

> kw
:abc

> (= kw :abc)
false

> (= :abc :abc)
true
```

**Comment by ktodyruik** [comment] 2016-02-16 23:27
FYI, I noticed this in the 'issue_166_string_ops' branch as I was trying out the new string functions.

**Comment by kanaka** [comment] 2016-02-17 15:20
@ktodyruik I'm not seeing that behavior. Are you certain you are on the most recent version of the branch (what git hash are you testing against)? Also, what version of mono do you have?

**Comment by ktodyruik** [comment] 2016-02-17 18:22
I built it using .NET 4.0 on Windows (not mono), and I checked out the
issue_166_string_ops branch.

Kerry

**Comment by ktodyruik** [comment] 2016-02-17 19:30
I just tried it with the main branch. The issue appears to be in the _equal_Q type comparison.

![debug](https://cloud.githubusercontent.com/assets/6691649/13122006/25783f76-d572-11e5-9c04-3e50e546bdda.png)

**Comment by kanaka** [comment] 2016-02-18 15:03
@ktodyruik interesting. But all the other tests work for you? For the statement `(= kw :abc)` you shouldn't be getting a MalSymbol passed to the `_equal_Q` function because the symbol should have been resolved to it's value from the environment (unless you intentional quote the symbol). I don't see that behavior myself with mono on Linux so I don't have a way to reproduce it in order to debug and come up with a fix. If it really is getting passed `_equal_Q` as a symbol, then the problem is more likely to be in `eval_ast` (where symbols are resolved in the environment) or `EVAL` (which sets up the call to `eval_ast`).

Also, are you using an unmodified source tree and are those complete (and only) commands that you ran? I only ask because the prompt should be `user>` and not `>`.

**Comment by ktodyruik** [comment] 2016-02-18 16:50
@kanaka Thanks. Good suggestions. I have been playing around with the source code. I'll make sure I'm testing on a clean copy and take a closer look.

**Comment by ktodyruik** [comment] 2016-02-18 16:57
@kanaka I just ran it on a fresh copy and it worked correctly. So I caused the bug somehow. Sorry to trouble you. :)

**Comment by kanaka** [comment] 2016-02-18 18:24
@ktodyruik glad you figured it out.

**Closed by kanaka** 2016-02-18 18:24 UTC

**Comment by ktodyruik** [comment] 2016-02-23 21:48
@kanaka I see my mistake now. I tried to create an alias from = to eq?.

I mistakenly wrote 
```
(defmacro! eq? =)
```
instead of 
```
(def! eq? =)
```

This caused the _equal_Q function to be a macro. Then, EVAL called macroexpand which evaluated the expression to false.
