### ISSUE TITLE
If macro expands to symbol it doesn't go through another EVAL

### ISSUE THREAD

**Issue by dubek** [kanaka/mal#142] opened 2016-01-20 17:53 UTC
The behaviour I encounter is a bit strange, but maybe I'm missing something (not sure my issue description is correct).

Here is the problematic scenario:

```
user> (let* [foo 123] (or false foo))
foo
```
I expected `123` as the result here.

Or with a simpler macro:

```
Mal [clojure]
user> (defmacro! nothing (fn* [x] x))
#object[clojure.lang.AFunction$1 0x2a341864 "clojure.lang.AFunction$1@2a341864"]
user> (nothing a)
a
```
I expected an exception `'a' not found`.

Note that if the macro expands to a list, then things seem OK:

```
user> (let* [foo 123] (or false (+ foo 0)))
123
```

I see the same behaviour in Clojure, Ruby, Python implementations.

Here is the fix status per implementation:

- [X] awk
- [X] bash
- [X] c
- [X] cpp
- [X] coffee
- [x] cs
- [x] clojure
- [X] crystal
- [X] d
- [X] elixir
- [X] erlang
- [X] es6
- [X] factor
- [X] forth
- [x] fsharp
- [X] go
- [x] groovy
- [X] guile
- [X] haskell
- [x] java
- [X] js
- [x] julia
- [X] kotlin
- [X] lua
- [X] make
- [X] mal
- [x] matlab
- [X] miniMAL
- [X] nim
- [X] ocaml
- [X] perl
- [X] php
- [X] ps
- [X] python
- [x] r
- [X] racket
- [x] rpython 
- [X] ruby
- [x] rust
- [x] scala
- [x] swift
- [X] tcl
- [x] vb
- [X] vimscript

**Comment by kanaka** [comment] 2016-01-20 21:31
Good catch! That's definitely a bug. I've pushed a soft test for step8 to get travis to do the coverage to determine which ones are broken:: https://travis-ci.org/kanaka/mal/builds/103705447

Not all of them are broken, for example awk and haskell and correct. The problem is that in EVAL after the call to macroexpand, we should call eval_ast if the macro result is not a list rather than just returning the ast.

**Comment by dubek** [comment] 2016-01-20 21:42
I assume the following paragraph in `guide.md` should be corrected:

```markdown
* In the evaluator (`EVAL`) before the special forms switch (apply
  section), perform macro expansion by calling the `macroexpand`
  function with the current value of `ast` and `env`. Set `ast` to the
  result of that call. If the new value of `ast` is no longer a list
  after macro expansion, then return `ast`, otherwise continue with
  the rest of the apply section (special forms switch).
```

And the process/*.txt files:

```
EVAL(ast,env):
  while true:
    if not list?(ast): return eval_ast(ast, env)

    ast = macroexpand(ast, env)
    if not list?(ast): return ast

    switch ast[0]:
      'def!:        return env.set(ast[1], EVAL(ast[2], env))
...
```

**Comment by kanaka** [comment] 2016-01-20 21:49
Yep, exactly.

**Comment by ivern** [comment] 2016-01-22 04:15
I'm not sure why kotlin is marked as having a fix.  The test is soft failing on my end.  I'll have a fix shortly.

**Comment by kanaka** [comment] 2016-01-22 15:53
@ivern yep, the mal-in-mal implementation is one of the ones that needs fixing.

**Comment by kanaka** [comment] 2016-01-26 14:42
I updated the list to reflect what's been done rather than what's been merged.

**Comment by kanaka** [comment] 2016-01-26 20:20
I just merged the PR and pushed updates for the remaining ones. I also made the test mandatory. I'll close this once travis checks out: https://travis-ci.org/kanaka/mal/builds/104991412

**Comment by dubek** [comment] 2016-01-26 20:27
Before you close it, the `process/step{8,9,A}_*.txt` and `process/guide.md` should be fixed as discussed above in this issue.

**Comment by kanaka** [comment] 2016-01-26 21:05
Yep, thanks for the reminder.

**Comment by kanaka** [comment] 2016-01-26 21:33
Okay, travis passed and I pushed those minor updates.

**Closed by kanaka** 2016-01-26 21:33 UTC
